# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  datetime_string: '${{ env.get("RAPIDS_DATETIME_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cuopt-server
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: ${{ datetime_string }}_${{ head_rev }}
  script:
    content: |
      # We pass an explicit matrix-entry here along with `disable-cuda=true` to
      # avoid `rapids-build-backend` trying to use an unavailable `nvcc` to
      # lookup a `CUDA_VERSION` that we don't need for the conda build.
      python -m pip install -C rapidsai.disable-cuda=true -C rapidsai.matrix-entry='cuda=12.x;cuda_suffixed=true' ./python/cuopt_server

requirements:
  host:
    - pip
    - python >=3.11
    - rapids-build-backend >=0.4.0,<0.5.0
    - setuptools>=77.0.0
  run:
    - cuopt =${{ version }}
    - fastapi >=0.104.1
    - jsonref =1.1.0
    - msgpack-python =1.2.1
    - msgpack-numpy =0.4.8
    - numpy >=2.0,<3.0
    - pandas>=2
    - psutil>=6.0.0
    - python
    - uvicorn =0.34

tests:
  - python:
      imports:
        - cuopt_server
      pip_check: false

about:
  homepage: ${{ load_from_file("python/cuopt_server/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cuopt_server/pyproject.toml").project.license }}
  summary: ${{ load_from_file("python/cuopt_server/pyproject.toml").project.description }}
